version: '3.9'
services:
  dbTrain:
    container_name: dbTrain
    image: postgres
    environment:
      - POSTGRES_PASSWORD=train
      - POSTGRES_USER=train
      - POSTGRES_DB=db_train
      - PGDATA=/var/lib/postgresql/train_data
    ports:
      - "5430:5432"
    restart: always
  minio:
    image: minio/minio:latest
    container_name: minio_container
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      BUCKET_NAME: train-bucket
    ports:
      - "9000:9000"
      - "9003:9003"
    command: server /data --console-address ":9003"
  storage:
    container_name: storage
    build:
      context: ./services/storage
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbTrain:5432/db_train
      - SPRING_DATASOURCE_USERNAME=train
      - SPRING_DATASOURCE_PASSWORD=train
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS-KEY=minioadmin
      - MINIO_SECRET-KEY=minioadmin
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "9900:9900"
    depends_on:
      - dbTrain
      - minio
      - kafka
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  user_service:
    container_name: user_service
    build:
      context: ./services/user_service
      dockerfile: Dockerfile
    environment:
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8081:8081"
    depends_on:
      - kafka