apiVersion: apps/v1
kind: Deployment
metadata:
  name: user_service
  labels:
    app: user_service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user_service
  template:
    metadata:
      labels:
        app: user_service
    spec:
      containers:
        - name: user-pod
          image: boris86msk/user_service
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: user-pod-service
spec:
  selector:
    app: user_service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32100
